{% set version = "4.0.0" %}

package:
  name: dask-sphinx-theme
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dask-sphinx-theme/dask_sphinx_theme-{{ version }}.tar.gz
  sha256: 59594fba7b628372743a447bc5250495209c299d7bd9d29a018ab6f76f5ac9f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sphinx-book-theme 0.2.0
    - jsonschema

test:
  requires:
    - python {{ python_min }}
  imports:
    - dask_sphinx_theme

about:
  home: https://github.com/dask/dask-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Dask theme for Sphinx

extra:
  recipe-maintainers:
    - jakirkham
    - mrocklin
    - jrbourbeau
    - jacobtomlinson
